### PR TITLE
modified to inglude Google OAuth2 sign in

### PR DESCRIPTION
**Pull request by devasur**
Ran into a serious issue with Google+ button login last week.  Because of some changes on the Google side it just started to auto login users.  None of my efforts to configure the button to behave nicely worked.  Ended up changing the login to use the alternative and recommended Google Signin Button

https://developers.google.com/identity/sign-in/web/sign-in

Works nicely now.  I have modified the code to work with the global event listener paradigm of the original code.  One great benefit of using this approach is that even on localhost logout works nicely.

Check it out.  Currently in use on our production code
https://walkinto.in

### CODE REVIEW

**Comment by devasur** [comment]
@sirkitree Might want to take a loot at this?

**Comment by sirkitree** [comment]
I do, just haven't had time to test and I'll be gone today and all weekend
as well. This will require a major version bump. If anyone can test before
I get back I should certainly have time next week.

**Comment by sarbjeetsingh** [comment]
i am getting this error with your code, can you please tell me whats wrong

**Comment by devasur** [comment]
ClientId is the parameter you get for this Auth setup from your https://console.developers.google.com for your project.  You pass it as an attribute to your <google-plus-signin clientid='CLIENT_ID_FROM_DEVELOPER_CONSOLE'>
Usually in the format of  *.apps.googleusercontent.com

**Comment by Barryrowe** [comment]
I will be testing this today and report back on how it goes.

**Comment by Barryrowe** [comment]
@sarbjeetsingh btw, the error you're getting is because the new platforms script appears to expect the clientid to be set in a meta tag like:

    <meta name="google-signin-client_id" content="YOUR_CLIENT_ID.apps.googleusercontent.com" />

If I can get this working I'll try and add to extend this to dynamically generate that tag based on the directive attribute before loading the platforms script.

**Comment by Barryrowe** [comment]
FYI, I just submitted a Pull request to @devasur to extend his changes a little bit further. I've tested the auth2 changes and they work well. See PR https://github.com/devasur/angular-directive.g-signin/pull/1

**Comment by sirkitree** [comment]
Cool, I'll merge once they get in here.

**Comment by Barryrowe** [comment]
I don't know if @devasur is maintaining his fork. If you'd like @sirkitree I can submit a PR to a new branch on this repo.

**Comment by sirkitree** [comment]
That would also be acceptable. Thank you.

**Pull request closed without merging**
